### ISSUE TITLE
Need to add optimization for the state

### ISSUE THREAD

**Issue by R7B9** [Tiger-team-2679/Swerve2023#3]
https://github.com/Tiger-team-2679/Swerve2023/blob/66769f888b8776bc1135120c2c98b3df1f4f8ef9/src/main/java/frc/robot/subsystems/swerve/SwerveModule.java#L34-L42

**Comment by RBD120307** [comment]
lol i finished

**Comment by RBD120307** [comment]
hahahahhahahhahahahhahvhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhahhahahahhahahhahahahhah
